spring:
  batch:
    job:
      names: sample03Job
      # enabled: false  
  datasource:
    url: "jdbc:h2:mem:test"
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      # http://localhost:8080/h2-console
  sql:
    init:
      mode: always
      encoding: UTF-8